name: Update GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate classic metrics
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.svg
          token: ${{ secrets.METRICS_TOKEN || github.token }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          plugin_lines: yes

      - name: Generate languages metrics
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN || github.token }}
          user: ${{ github.repository_owner }}
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: lines, percentage

      - name: Generate repositories metrics
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics-repositories.svg
          token: ${{ secrets.METRICS_TOKEN || github.token }}
          user: ${{ github.repository_owner }}
          template: classic
          base: ""
          plugin_repositories: yes
          plugin_repositories_order: featured
          plugin_repositories_featured: omnius-labs/axus, omnius-labs/core-rs, omnius-labs/core-cs, omnius-labs/core-swift, omnius-labs/core-go, omnius-labs/core-scala, lyrise/tredir-rs, lyrise/uredir-rs, lyrise/fredir-rs

      - name: Commit metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/metrics*.svg
          git commit -m "Update GitHub metrics" || exit 0
          git push
